
<style>
.msgbod{
	display: inline-block;
    position: relative;
    top: 0;
    bottom: 0;
    left: 20%;
    right: 20%;
    width: 750px;
    height: 120px;
    margin: auto;
    background-color: #f2f2f2;
    border: 1px solid #dddddd;
    padding: 10px;
    border-radius: 5px;
    box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.1);
}

table {
    font-family: Arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
}

td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
}

.page-title-wrapper {
    text-align: center;
}

.primary {
    text-align: center;
    margin-top: 20px;
}

.action.primary.continue {
    background-color: #4CAF50;
    border: none;
    color: white;
    padding: 19px 295px;
    margin-left: 8px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    border-radius: 5px;
    cursor: pointer;
    transition: background-color 0.3s ease;
}

media="screen and (min-width: 768px)"
@media (min-width: 769px), print
.actions-toolbar .primary .action {
    margin: 0 0px 0 0;
}

.action.primary.continue:hover {
    background-color: #45a049;
}

</style>
<div class="msgbod">
    <h3 style="text-align: center;">Shurjopay Have Received Your Payment Successfully!</h3>
    <div class="actions-toolbar">
        <div class="primary">
            <a href="\"><button class="action primary continue">Continue Shopping</button></a>
        </div>
    </div>
</div>